language: kotlin

services:
  - docker

after_success:
  - docker build -t "$DOCKER_USERNAME"/dms:1 .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/dms:1

jdk:
  - openjdk11

script: mvn clean install

cache:
  directories:
  - node_modules
