language: kotlin

deploy:
  provider: cloudfoundry
  username: $CLOUD_FOUNDRY_USER
  password: $CLOUD_FOUNDRY_PASSWORD
  api: https://api.run.pivotal.io
  organization: $CLOUD_FOUNDRY_ORG
  space: development
  app_name: dms
  

jdk:
  - openjdk11

script: mvn clean install

cache:
  directories:
  - node_modules
