language: kotlin

services:
  - docker

after_success:
  - docker build -t 1 .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push silviod92/dms:1

jdk:
  - openjdk11

script: mvn clean install

cache:
  directories:
  - node_modules
